name: "CMS"
description: Submit an issue about the W3C Craft CMS
labels: [ "cms" ]
assignees: [ ]
body:
  - type: textarea
    id: issue
    attributes:
      label: Describe the issue
      description: A clear and concise description of what the issue is.
      # placeholder:
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: To reproduce
      placeholder: Steps to reproduce the behavior, including URLs.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
